// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/_debug/public-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_debug/public-config.get').default>>>>
    }
    '/api/_health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_health.get').default>>>>
    }
    '/api/debug-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-config.get').default>>>>
    }
    '/api/debug-env': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-env.get').default>>>>
    }
    '/api/listings': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings.post').default>>>>
    }
    '/api/listings/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/[id].patch').default>>>>
    }
    '/api/media/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/media/upload.post').default>>>>
    }
    '/api/properties': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties.post').default>>>>
    }
    '/api/properties/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/[id].patch').default>>>>
    }
    '/api/property-media': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/property-media.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/property-media.post').default>>>>
    }
    '/api/property-media/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/property-media/[id].delete').default>>>>
    }
    '/api/property-media/reorder': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/property-media/reorder.post').default>>>>
    }
    '/api/supa-storage': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/supa-storage.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}